### ISSUE TITLE
Error in real-time plots

### ISSUE THREAD

**Issue by esantamariavazquez** [medusabci/medusa-platform#58]
Sometimes, the real time plots panel throws this error:

Traceback (most recent call last):
  File "C:\Users\edusa\MEDUSA\v2023\src\gui\plots_panel\real_time_plots.py", line 823, in update_plot
    self.append_data(chunk_times, chunk_signal)
  File "C:\Users\edusa\MEDUSA\v2023\src\gui\plots_panel\real_time_plots.py", line 745, in append_data
    time_in_graph = np.insert(
  File "<__array_function__ internals>", line 180, in insert
  File "C:\Users\edusa\MEDUSA\v2023\venv\lib\site-packages\numpy\lib\function_base.py", line 5332, in insert
    raise IndexError(f"index {obj} is out of bounds for axis {axis} "
IndexError: index 31 is out of bounds for axis 0 with size 25

MEDUSA exception report:
        Exception in function None
        Process: MainProcess
        Thread: MainThread
        UID: None
        Importance: unknown
        Custom message: None
        Scope: None
        Exception type: IndexError
        Exception msg: index 31 is out of bounds for axis 0 with size 25

**Comment by yangyang1018** [comment]
The websites https://docs.www.medusabci.com/medusa-platform/ and https://www.medusabci.com/ are no longer available, what is happening and what is causing them to be unavailable?

**Comment by esantamariavazquez** [comment]
> The websites https://docs.www.medusabci.com/medusa-platform/ and https://www.medusabci.com/ are no longer available, what is happening and what is causing them to be unavailable?

Dear @yangyang1018, 

We are solving some technical issues in our server. We expect to solve it today. Sorry for the inconvenience. 

Kind regards,
Eduardo Santamaría.

**Comment by yangyang1018** [comment]
Dear Eduardo Santamaría,
Thank you for your reply, it would be a pleasure if this could be resolved as soon as possible! Thank you for your contribution!
Kind regards,
yang Yang



---- Replied Message ----
| From | Eduardo ***@***.***> |
| Date | 10/15/2023 20:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [medusabci/medusa-platform] Error in real-time plots (Issue #58) |

The websites https://docs.www.medusabci.com/medusa-platform/ and https://www.medusabci.com/ are no longer available, what is happening and what is causing them to be unavailable?

Dear @yangyang1018,

We are solving some technical issues in our server. We expect to solve it today. Sorry for the inconvenience.

Kind regards,
Eduardo Santamaría.

**Comment by esantamariavazquez** [comment]
Dear @yangyang1018,

We just solved the issue and everything is working now. Sorry again for the inconvenience!

Kind regards,
Eduardo.

**Comment by yangyang1018** [comment]
Dear Eduardo，


Thanks again for all you do.
Kind regards,
yang Yang













At 2023-10-16 15:55:10, "Eduardo Santamaría-Vázquez" ***@***.***> wrote:

Dear @yangyang1018,

We just solved the issue and everything is working now. Sorry again for the inconvenience!

Kind regards,
Eduardo.
